sudo: required

services:
  - docker

language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest -v
  
after_success:
  - sh .travis/deploy_dockerhub.sh